const Color = Object.freeze({
    DEFAULT_FILL: [255, 255, 255, 0.7],
    DEFAULT_STROKE: '#0064fa',
    SELECTION_STROKE: 'yellow',
    SELECTION_FILL: 'yellow',
    MEASURE_INTERACTION_FILL: 'rgba(255, 255, 255, 0.2)',
    MEASURE_INTERACTION_STROKE: '#8bc34a',
    DEFAULT_CARTOGRAPHIC_MEASURE: 'orange',
    DEFAULT_REAL_MEASURE: 'blue',
    DEFAULT_AUXELEMENT_STROKE: 'green',
    DEFAULT_REFERENCE_POINT_FILL: '#FF0000'
});

export default Color;